- source/demonstrate_knapsack_solvers.py:
    - description: Ensure that demonstrate_knapsack_solvers.py file exists in the source/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for demonstrate_knapsack_solvers.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in demonstrate_knapsack_solvers.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 14
        exact: false
    - description: Create a sufficient number of single-line comments in demonstrate_knapsack_solvers.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 5
        exact: false

# perform checks on a file
- writing/reflection.md:
    - description: Ensure that the reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for reflection.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Write a minimum number of meaningful words in the reflection
      check: CountFileWords
      options:
        count: 250
        exact: false
    - description: Confirm that the markdown file has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 11
        exact: false
    - description: Confirm that the markdown file has the correct number of fenced code blocks
      check: CountMarkdownTags
      options:
        tag: code_block
        count: 1
        exact: false

# run the program and confirm the existence of fragments in its output
- description: Run the demonstrate_knapsack_solvers.py program and confirm the correct number of non-blank lines in the output
  check: CountCommandOutput
  options:
    command: "python source/demonstrate_knapsack_solvers.py"
    count: 22
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the demonstrate_knapsack_solvers.py program and confirm label content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/demonstrate_knapsack_solvers.py"
    fragment: "Running all of the knapsack solvers!"
    count: 1
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the demonstrate_knapsack_solvers.py program and confirm size content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/demonstrate_knapsack_solvers.py"
    fragment: "knapsack of size 20"
    count: 4
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the demonstrate_knapsack_solvers.py program and confirm only one selection of computer"
  check: MatchCommandFragment
  options:
    command: "python source/demonstrate_knapsack_solvers.py"
    fragment: "(Computer, 200, 20)"
    count: 1
    exact: true

# confirm a suitable number of commit messages
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 5
